name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Instalar Python 
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Ejecutar Python Propio
      run: |
        cd src
        python Propio.py
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "AÃ±adir data por proceso interno"
        branch: main
        # Optional glob pattern of files which should be added to the commit
        #file_pattern: /

        # Optional local file path to the repository
        repository: .

        # Optional commit user and author settings
        commit_user_name: Actions Bot
        commit_user_email: lmonsalve22@gmail.com
        commit_author: github bot <lmonsalve22@gmail.com>
        push_options: '--force'
